repos:
  # Note: We need to redeclare access_spack_packages above builtin in this scope
  # otherwise builtin will resolve to a higher precedence than our
  # access_spack_packages, which errors out sometimes where we have our own
  # reimplementation (eg. fiat).
  # The actual branch/destination values are still taken from lower scopes.
  access_spack_packages:
    git: https://github.com/ACCESS-NRI/access-spack-packages.git
  builtin: $CALLER_REPOSITORY_PATH/repos/spack_repo/builtin
